### ISSUE TITLE
If the connecter (latest branch) is run on an agent server, the manager attribute is updated

### ISSUE THREAD

**Issue by Rick-Jongbloed** [Tools4everBV/HelloID-Conn-Prov-Target-EntraID#10]
Cloud:
14:03:32.41
Account property(s) required to update: jobTitle
 
14:03:32.41
Compared current account to mapped properties. Result: Update
 
14:03:32.41
Check if current account can be found. Result: Update
 
OnPrem:
 
14:04:09.63
Account property(s) required to update: jobTitle, manager
 
14:04:09.63
Compared current account to mapped properties. Result: Update
 
14:04:09.63
Check if current account can be found. Result: Update

**Comment by rhouthuijzen** [comment]
This is already fixed in a previous update.
