### ISSUE TITLE
field mapping for authenticationMethods

### ISSUE THREAD

**Issue by mouki9** [Tools4everBV/HelloID-Conn-Prov-Target-EntraID#15]
The field mapping for the email and phone authenticationmethods are not used, instead the values used are hardcoded in the PowerShell scripts. Could this be changed? 
This has been detected when using correlate only option.

**Comment by rschouten97** [comment]
@mouki9 could you elaborate on this?
And how would you like to see this?
We moved this excplicitly to the code in the authenticationMethods script themselves to avoid complex fieldmapping.

All account fields are mapped at the fieldmapping, however this is a permission, therefore the mapping has to take place in the permissions itself.

**Comment by mouki9** [comment]
> @mouki9 could you elaborate on this? And how would you like to see this? We moved this excplicitly to the code in the authenticationMethods script themselves to avoid complex fieldmapping.
> 
> All account fields are mapped at the fieldmapping, however this is a permission, therefore the mapping has to take place in the permissions itself.

If I look in the permission part, there is an explicit fieldmapping.json. 
![image](https://github.com/user-attachments/assets/097cf814-a612-4c61-8f0c-9e396ef106cc)
The assumption is that this fieldmapping is there for a reason? But when adding the assignment this is totally ignored? Either way works for me, but at least make it consistent. If not used, then make sure the fieldmapping is removed from the permissions part! Also in the readme there is no additional information on how to configure this part.

**Comment by rhouthuijzen** [comment]
Fixed in PR
